version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://db:27019
    depends_on:
      - db

  db:
    image: mongo:4
    container_name: mongodb
    ports:
      - "27019:27019"
    volumes:
      - mongodb_data:/data/db
    entrypoint: >
      sh -c "
      mongod --port 27019 --replSet rs0 --bind_ip_all &
      sleep 5 &&
      mongo --port 27019 --eval 'rs.initiate()' &&
      tail -f /dev/null
      "

volumes:
  mongodb_data: