openapi: 3.0.0
info:
  title: UserBuy API
  description: API for managing products, users, purchases, and roles
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /products:
    post:
      summary: Add product (ADMIN ONLY)
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                name:
                  type: string
                price:
                  type: number
                  format: float
                stock_quantity:
                  type: integer
                currency:
                  type: string
      responses:
        '200':
          description: Product added successfully
    get:
      summary: Get products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                      format: float
                    stock_quantity:
                      type: integer
                    currency:
                      type: string

  /products/{productId}:
    put:
      summary: Update product (ADMIN ONLY)
      operationId: updateProduct
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                name:
                  type: string
                price:
                  type: number
                  format: float
                stock_quantity:
                  type: integer
                currency:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Product updated successfully
    delete:
      summary: Delete product (ADMIN ONLY)
      operationId: deleteProduct
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully

  /users:
    post:
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User created successfully

  /users/{userId}/roles:
    patch:
      summary: Update roles (ADMIN ONLY)
      operationId: updateRoles
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
      responses:
        '200':
          description: User role updated successfully
